overrides:
  adm-zip: 0.6.0
  sharp: 0.35.4

allowBuilds:
  esbuild: set this to true or false
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@orcareplay/core@0.2.1'
  - '@orcareplay/plugin-api@0.2.1'
  - '@orcareplay/schema@0.2.1'
  - '@orcareplay/viewer@0.2.1'
