import assert from 'node:assert/strict'
import test from 'node:test'
import {CodeIntelligenceAdapterV1} from '../../../../src/dsh/lisp/code-intelligence.js'
import {codeOutcome,type CodeResponseV1,type CodeIntelligenceServiceV1,type CodeRequestV1} from '../../../../src/dsh/lisp/code-intelligence-contracts.js'
import {renderResult} from '../../../../src/dsh/lisp/model-result.js'
const signal=new AbortController().signal
const opened:CodeResponseV1={...codeOutcome('ok','opened'),freshness:'current',snapshotVersion:'version-1',inputBytes:10,data:{handle:'snapshot',path:'index.ts',language:'typescript',parseErrors:false}}
function fixture(handler:(request:CodeRequestV1,signal:AbortSignal)=>Promise<CodeResponseV1>=async()=>opened) {
 let valid=true,disposed=0,calls=0
 const binding={owner:{agentId:'agent',sessionId:'session'},workspaceRoot:'/workspace',scope:{},context:{get(){return undefined}},assertCurrent(){if(!valid)throw new Error('scope changed')}}
 let provider:unknown={version:1,capabilities:['snapshots','structure','semantic'],async bind(){return {async request(request:CodeRequestV1,signal:AbortSignal){calls++;return handler(request,signal)},async dispose(){disposed++}}}} satisfies CodeIntelligenceServiceV1
 const adapter=new CodeIntelligenceAdapterV1(binding,()=>provider)
 return {adapter,revoke(){valid=false},set(value:unknown){provider=value},get calls(){return calls},get disposed(){return disposed}}
}
test('absence and unknown contract never fall back to generic tools',async()=>{const f=fixture();for(const [provider,reason] of [[undefined,'provider_missing'],[{version:2},'provider_version'],[{version:1,capabilities:['exec']},'provider_contract']] as const){f.set(provider);assert.equal((await f.adapter.request('code-capabilities',{},signal)).reason,reason)}assert.equal(f.calls,0);await f.adapter.dispose()})
test('strict fixed DTOs reject identity, workspace, arbitrary query and semantic writes',async()=>{const f=fixture();for(const [method,args] of [['code-open',{path:'index.ts',root:'/other'}],['code-query',{handle:'snapshot',queryId:'(identifier) @secret'}],['code-semantic',{handle:'snapshot',kind:'rename',position:{line:0,character:0}}],['code-open',{path:'index.ts',method:'capabilities'}],['execute',{command:'anything'}]] as const)await assert.rejects(f.adapter.request(method,args,signal),{code:'CODE_INVALID_INPUT'});assert.equal(f.calls,0);await f.adapter.dispose()})
test('leases revoke handles at evaluation end and release is idempotent',async()=>{const f=fixture();assert.equal((await f.adapter.request('code-open',{path:'index.ts'},signal)).status,'ok');await f.adapter.request('code-release',{handle:'snapshot'},signal);assert.equal((await f.adapter.request('code-outline',{handle:'snapshot'},signal)).status,'stale');await f.adapter.request('code-release',{handle:'snapshot'},signal);await f.adapter.dispose();await f.adapter.dispose();assert.equal(f.disposed,1);assert.equal((await f.adapter.request('code-open',{path:'index.ts'},signal)).status,'stale')})
test('schema rejects provider write commands, oversized payloads and missing freshness',async()=>{for(const bad of [{...opened,extra:'secret'},{...opened,freshness:'unknown'},{...opened,data:{...(opened.data as object),command:'exec'}},{...opened,data:{...(opened.data as object),path:'x'.repeat(4097)}}]){const f=fixture(async()=>bad as CodeResponseV1);assert.equal((await f.adapter.request('code-open',{path:'index.ts'},signal)).reason,'provider_invalid_response');await f.adapter.dispose()}})
test('call budget includes failed provider attempts and cleanup works after exhaustion',async()=>{const f=fixture();f.set(undefined);for(let i=0;i<100;i++)assert.equal((await f.adapter.request('code-capabilities',{},signal)).status,'unavailable');assert.equal((await f.adapter.request('code-capabilities',{},signal)).status,'limit_exceeded');assert.equal((await f.adapter.request('code-release',{handle:'unknown'},signal)).status,'ok');await f.adapter.dispose()})
test('noncooperative late result is discarded on cancellation and lease is disposed',async()=>{let finish!:(response:CodeResponseV1)=>void;const f=fixture(async()=>new Promise(resolve=>{finish=resolve}));const abort=new AbortController();const pending=f.adapter.request('code-open',{path:'index.ts'},abort.signal);await new Promise(resolve=>setImmediate(resolve));abort.abort();assert.equal((await pending).status,'cancelled');finish(opened);await f.adapter.dispose();assert.equal(f.disposed,1)})
test('provider realm replacement and owner revocation discard in-flight results',async()=>{let finish!:(response:CodeResponseV1)=>void;const f=fixture(async()=>new Promise(resolve=>{finish=resolve}));const pending=f.adapter.request('code-open',{path:'index.ts'},signal);await new Promise(resolve=>setImmediate(resolve));f.set(undefined);finish(opened);assert.equal((await pending).status,'stale');await f.adapter.dispose();const g=fixture();g.revoke();await assert.rejects(g.adapter.request('code-capabilities',{},signal),/scope changed/);assert.equal(g.calls,0)})
test('model rendering preserves code outcome metadata under reduction',()=>{const code={...opened,status:'partial',reason:'parse_errors',omitted:3,truncated:true,data:{items:Array.from({length:200},()=>({text:'x'.repeat(5000)}))}};const rendered=renderResult({ok:true,operationId:'fixture',value:{json:code}}),result=JSON.parse(rendered);assert.equal(result.value.json.status,'partial');assert.equal(result.value.json.reason,'parse_errors');assert.equal(result.value.json.snapshotVersion,'version-1');assert.ok(Buffer.byteLength(rendered)<=16384)})

test('an existing lease cannot be reused after replacement by another V1 realm',async()=>{const f=fixture();await f.adapter.request('code-open',{path:'index.ts'},signal);f.set({version:1,capabilities:['snapshots','structure','semantic'],bind(){throw new Error('must not bind')}});assert.equal((await f.adapter.request('code-outline',{handle:'snapshot'},signal)).status,'stale');assert.equal(f.calls,1);await f.adapter.dispose()})

test('caller deadline and cancellation remain distinct outcomes',async()=>{const f=fixture(async()=>new Promise(()=>{}));const result=await f.adapter.request('code-open',{path:'index.ts'},AbortSignal.timeout(20));assert.equal(result.status,'timeout');assert.equal(result.reason,'caller_deadline');await f.adapter.dispose()})

test('a code failure in an omitted array page remains visible in model outcomes',()=>{const values=Array.from({length:80},()=>({...opened,data:{text:'x'.repeat(2000)}}));values.push({...codeOutcome('timeout','operation_deadline')} as any);const output=JSON.parse(renderResult({ok:true,operationId:'fixture',value:{json:values}}));assert.equal(output.codeOutcomes.statuses.timeout,1);assert.equal(output.codeOutcomes.statuses.ok,80);assert.equal(output.codeOutcomes.total,81)})


test('provider lookup errors are explicit unavailable outcomes',async()=>{const adapter=new CodeIntelligenceAdapterV1({owner:{agentId:'a',sessionId:'s'},workspaceRoot:'/workspace',scope:{},context:{get(){}},assertCurrent(){}},()=>{throw new Error('realm stopped')});assert.equal((await adapter.request('code-capabilities',{},signal)).reason,'provider_resolution');await adapter.dispose()})
test('source budget is cumulative across successful opens',async()=>{
 const input=fixture(async()=>({...opened,inputBytes:2097152}));for(let i=0;i<8;i++)assert.equal((await input.adapter.request('code-open',{path:'index.ts'},signal)).status,'ok');assert.equal((await input.adapter.request('code-open',{path:'index.ts'},signal)).status,'limit_exceeded');await input.adapter.dispose()
})

test('adapter rejects semantic locations outside the host workspace',async()=>{const f=fixture(async request=>request.method==='snapshot.open'?opened:{...opened,inputBytes:undefined,data:{items:[{uri:'file:///outside/secret.ts',range:{start:{line:0,character:0},end:{line:0,character:1}}}]}} as any);await f.adapter.request('code-open',{path:'index.ts'},signal);assert.equal((await f.adapter.request('code-semantic',{handle:'snapshot',kind:'definition',position:{line:0,character:0}},signal)).status,'unavailable');await f.adapter.dispose()})


test('response budget cannot be bypassed with many individually valid frames',async()=>{const f=fixture(async request=>request.method==='snapshot.open'?opened:request.method==='structure.outline'?{...opened,inputBytes:undefined,data:{items:[{handle:'node',kind:'function_declaration',range:{start:{line:0,character:0},end:{line:0,character:8000}}}]}} as any:{...opened,inputBytes:undefined,data:{text:'x'.repeat(8000),range:{start:{line:0,character:0},end:{line:0,character:8000}}}} as any);await f.adapter.request('code-open',{path:'index.ts'},signal);await f.adapter.request('code-outline',{handle:'snapshot'},signal);for(let i=0;i<7;i++)assert.equal((await f.adapter.request('code-span',{nodeHandle:'node'},signal)).status,'ok');assert.equal((await f.adapter.request('code-span',{nodeHandle:'node'},signal)).status,'limit_exceeded');assert.equal((await f.adapter.request('code-release',{handle:'snapshot'},signal)).status,'ok');await f.adapter.dispose()})
test('release failures revoke local handles and do not skip final disposal',async()=>{const f=fixture(async request=>{if(request.method==='snapshot.release')throw new Error('broken cleanup');return opened});await f.adapter.request('code-open',{path:'index.ts'},signal);assert.equal((await f.adapter.request('code-release',{handle:'snapshot'},signal)).reason,'release_failed');assert.equal((await f.adapter.request('code-outline',{handle:'snapshot'},signal)).status,'stale');await f.adapter.dispose();assert.equal(f.disposed,1)})
