(defpackage :kioku.internal (:use :cl) (:export :serve :object :rpc :*proposals* :*inputs* :*objects* :*generation*))
(defpackage :kioku.data (:use :cl) (:export :parse-json :encode-json :parse-jsonl :map-jsonl :read-csv :write-csv :read-tsv :write-tsv :regex-matches :regex-replace))
(defpackage :kioku.files (:use :cl) (:export :input :read-text :write-text :propose-write :propose-delete :scratch :search-text :diff-text))
(defpackage :kioku.objects (:use :cl) (:export :retain :inspect-ref :release :register-artifact))
(defpackage :kioku.process (:use :cl) (:export :run :python :shell :start-job :job-status :cancel-job))
(defpackage :kioku.environment (:use :cl) (:export :status))
(defpackage :kioku.tools (:use :cl) (:export :describe-tools :describe-symbol :available-tools :call-tool))
(defpackage :kioku.user (:use :cl))
(in-package :kioku.internal)
(defvar *wire*)
(defvar *proposals* nil)
(defvar *inputs* #())
(defvar *objects* (make-hash-table :test 'equal))
(defvar *generation* (uiop:getenv "KIOKU_GENERATION"))
(defvar *counter* 0)
(defvar *request* nil)
(defun object (&rest pairs)
  (let ((h (make-hash-table :test 'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key h) value)) h))
(defun emit (value)
  (let ((line (kioku.data:encode-json value)))
    (when (> (length (sb-ext:string-to-octets line :external-format :utf-8)) 1048575) (error "FRAME_TOO_LARGE"))
    (write-line line *wire*) (finish-output *wire*)))
(defun receive ()
  (let ((line (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
    (loop for char = (read-char *wire* nil nil)
          do (unless char (return-from receive nil))
             (when (char= char #\Newline) (return))
             (when (>= (length line) 1048576) (error "FRAME_TOO_LARGE"))
             (vector-push-extend char line))
    (kioku.data:parse-json line)))
(defun rpc (method arguments)
  (let ((id (format nil "rpc-~D" (incf *counter*))))
    (emit (object "version" 1 "type" "rpc" "id" id "request" *request* "method" method "arguments" arguments))
    (let ((reply (receive)))
      (unless (and reply (equal id (gethash "id" reply))) (error "RPC_MISMATCH"))
      (unless (eq yason:true (gethash "ok" reply)) (error "~A" (gethash "error" reply)))
      (gethash "value" reply))))
(defun printed (value)
  ;; print-length bounds elements, not arbitrary strings; the host independently caps frames/output.
  (let ((*print-length* 30) (*print-level* 6) (*print-circle* t) (*print-pretty* nil))
    (let ((text (prin1-to-string value))) (subseq text 0 (min 16000 (length text))))))
(defun evaluate-code (code)
  (let ((*package* (find-package :kioku.user)) (*read-eval* nil) (last nil))
    (with-input-from-string (in code)
      (loop for form = (read in nil in) until (eq form in) do (setf last (multiple-value-list (eval form)))))
    (object "printed" (printed last) "ref" (kioku.objects:retain (first last))
            "json" (handler-case
                        (let ((json (kioku.data:encode-json (first last))))
                          (if (< (length json) 16000) (kioku.data:parse-json json) nil))
                      (error () nil)))))
(defun serve ()
  (setf *wire* (sb-sys:make-fd-stream 3 :input t :output t :element-type 'character :external-format :utf-8 :buffering :line))
  (emit (object "version" 1 "type" "ready"))
  (loop for request = (receive) while request do
    (let ((*request* (gethash "id" request)) (*proposals* nil) (*inputs* (gethash "inputs" request #())))
      (handler-case
          (let ((value (cond ((equal "eval" (gethash "method" request)) (evaluate-code (gethash "code" request)))
                             ((equal "describe" (gethash "method" request)) (kioku.tools:describe-symbol (gethash "symbol" request "")))
                             ((equal "inspect" (gethash "method" request)) (kioku.objects:inspect-ref (gethash "ref" request)))
                             (t (error "UNKNOWN_METHOD")))))
            (emit (object "version" 1 "type" "result" "id" *request* "ok" yason:true "value" value "proposals" (coerce (reverse *proposals*) 'vector))))
        (error (condition)
          (emit (object "version" 1 "type" "result" "id" *request* "ok" yason:false "value" (let ((text (princ-to-string condition))) (subseq text 0 (min 4000 (length text)))) "proposals" #())))))))
(in-package :kioku.data)
(defun parse-json (text)
  (let ((yason:*parse-json-arrays-as-vectors* t) (yason:*parse-json-booleans-as-symbols* t) (*read-eval* nil)) (yason:parse text)))
(defun encode-json (value) (with-output-to-string (s) (yason:encode value s)))
(defun read-csv (text) (cl-csv:read-csv text))
(defun write-csv (rows) (with-output-to-string (s) (cl-csv:write-csv rows :stream s)))
(defun read-tsv (text) (cl-csv:read-csv text :separator #\Tab))
(defun write-tsv (rows) (with-output-to-string (s) (cl-csv:write-csv rows :stream s :separator #\Tab)))
(defun map-jsonl (function stream &key (max-line-length 65536))
  "Call FUNCTION for each JSON value, reading at most MAX-LINE-LENGTH characters per line."
  (let ((line (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)) (count 0))
    (labels ((flush-line () (when (plusp (length (string-trim '(#\Space #\Tab #\Return) line))) (funcall function (parse-json line)) (incf count)) (setf (fill-pointer line) 0)))
      (loop for char = (read-char stream nil nil) while char do
        (if (char= char #\Newline) (flush-line)
            (progn (when (>= (length line) max-line-length) (error "JSONL_LINE_LIMIT")) (vector-push-extend char line))))
      (flush-line)) count))
(defun parse-jsonl (text)
  (let ((items nil) (count 0))
    (with-input-from-string (stream text)
      (map-jsonl (lambda (value) (when (> (incf count) 10000) (error "JSONL_ITEM_LIMIT: use map-jsonl")) (push value items)) stream))
    (coerce (nreverse items) 'vector)))
(defun regex-matches (pattern text) (cl-ppcre:all-matches-as-strings pattern text))
(defun regex-replace (pattern text replacement) (cl-ppcre:regex-replace-all pattern text replacement))
(in-package :kioku.files)
(defun scratch () (pathname (uiop:getenv "KIOKU_SCRATCH")))
(defun input (index) (aref kioku.internal:*inputs* index))
(defun read-text (path) (uiop:read-file-string path))
(defun write-text (path text) (with-open-file (s path :direction :output :if-exists :supersede :if-does-not-exist :create) (write-string text s)) path)
(defun propose-write (path content)
  (when (>= (length kioku.internal:*proposals*) 100) (error "PROPOSAL_LIMIT"))
  (push (kioku.internal:object "operation" "write" "path" path "content" content) kioku.internal:*proposals*) path)
(defun propose-delete (path)
  (when (>= (length kioku.internal:*proposals*) 100) (error "PROPOSAL_LIMIT"))
  (push (kioku.internal:object "operation" "delete" "path" path) kioku.internal:*proposals*) path)
(defun search-text (pattern paths &key (limit 1000))
  "Search explicitly selected input/scratch files; return bounded line excerpts."
  (let ((hits nil))
    (dolist (path paths)
      (with-open-file (stream path)
        (loop for line = (read-line stream nil nil) for number from 1 while line do
          (when (cl-ppcre:scan pattern line)
            (when (>= (length hits) (min limit 1000)) (return-from search-text (nreverse hits)))
            (push (kioku.internal:object "path" (namestring (pathname path)) "line" number "text" (subseq line 0 (min 400 (length line)))) hits)))))
    (nreverse hits)))
(defun diff-text (before after)
  "Produce a bounded whole-file text diff; no host files are changed."
  (when (> (+ (length before) (length after)) 262144) (error "DIFF_LIMIT"))
  (if (equal before after) ""
      (with-output-to-string (out)
        (format out "--- before~%+++ after~%")
        (dolist (pair (list (cons #\- before) (cons #\+ after)))
          (with-input-from-string (in (cdr pair))
            (loop for line = (read-line in nil nil) while line do (format out "~C~A~%" (car pair) line)))))))
(in-package :kioku.objects)
(defun retain (value)
  (when (>= (hash-table-count kioku.internal:*objects*) 1000) (error "REFERENCE_LIMIT: release references or reset"))
  (let ((id (format nil "~A/~D" kioku.internal:*generation* (incf kioku.internal::*counter*))))
    (setf (gethash id kioku.internal:*objects*) value) id))
(defun inspect-ref (id)
  (multiple-value-bind (value present) (gethash id kioku.internal:*objects*)
    (unless present (error "STALE_REFERENCE"))
    (kioku.internal:object "ref" id "type" (princ-to-string (type-of value)) "printed" (kioku.internal::printed value))))
(defun release (id) (remhash id kioku.internal:*objects*))
(defun register-artifact (scratch-relative-path)
  (kioku.internal:rpc "artifact" (kioku.internal:object "path" scratch-relative-path)))
(in-package :kioku.process)
(defun run (program arguments &key (timeout-ms 120000))
  (kioku.internal:rpc "run" (kioku.internal:object "program" program "argv" (coerce arguments 'vector) "timeoutMs" timeout-ms)))
(defun python (code &key (timeout-ms 120000)) (run "python3" (list "-I" "-c" code) :timeout-ms timeout-ms))
(defun shell (code &key (timeout-ms 120000)) (run "sh" (list "-c" code) :timeout-ms timeout-ms))
(defun start-job (program arguments &key (timeout-ms 120000))
  (kioku.internal:rpc "start-job" (kioku.internal:object "program" program "argv" (coerce arguments 'vector) "timeoutMs" timeout-ms)))
(defun job-status (id) (kioku.internal:rpc "job-status" (kioku.internal:object "id" id)))
(defun cancel-job (id) (kioku.internal:rpc "cancel-job" (kioku.internal:object "id" id)))
(in-package :kioku.environment)
(defun status () (kioku.internal:object "generation" kioku.internal:*generation* "sbcl" (lisp-implementation-version) "os" (software-type) "architecture" (machine-type) "scratch" (namestring (kioku.files:scratch)) "network" yason:false "hostWrites" "proposals only" "libraries" #("yason" "cl-ppcre" "cl-csv")))
(in-package :kioku.tools)
(defun available-tools () (kioku.internal:rpc "tools-list" (kioku.internal:object)))
(defun call-tool (name &optional (arguments (kioku.internal:object)))
  (kioku.internal:rpc "tool-call" (kioku.internal:object "name" name "args" arguments)))
(defun describe-tools ()
  (mapcar (lambda (package) (cons package (sort (loop for symbol being the external-symbols of (find-package package) collect (symbol-name symbol)) #'string<)))
          '("KIOKU.TOOLS" "KIOKU.PROCESS" "KIOKU.FILES" "KIOKU.DATA" "KIOKU.OBJECTS" "KIOKU.ENVIRONMENT")))
(defun describe-symbol (name)
  (if (zerop (length name)) (kioku.internal::printed (describe-tools))
      (let* ((*read-eval* nil) (symbol (read-from-string name)))
        (unless (and (symbolp symbol) (member (package-name (symbol-package symbol)) '("KIOKU.TOOLS" "KIOKU.PROCESS" "KIOKU.FILES" "KIOKU.DATA" "KIOKU.OBJECTS" "KIOKU.ENVIRONMENT") :test #'equal)) (error "UNKNOWN_SYMBOL"))
        (kioku.internal:object "symbol" name "arguments" (kioku.internal::printed (sb-introspect:function-lambda-list symbol)) "documentation" (or (documentation symbol 'function) "See bundled kiokuko-lisp Skill.")))))
